#!/bin/bash

_run_python_code() {
    python3${pVer%.*} -c "$1"
}

_run() {
    echo "• Starting Deployment . . ."
    $(_run_python_code '
import os
import glob
import shutil

os.system("git clone https://github.com/Craboli83/bomber/ mybomber")

shutil.rmtree("/app/bomber/")
shutil.copytree("/app/mybomber/bomber/", "/app/bomber/")
shutil.rmtree("./mybomber")
')
    echo "• Deployment Completed!"
}

_start_bot () {
    python3 -m bomber
}

_run
_start_bot
